version: '3.5'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/portainer:/data

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
#    ports:
#      - 3306:3306
    networks:
      - backupnet
    volumes:
      - ${DATAROOT}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudusr
      - MYSQL_PASSWORD=${MYSQLPASSWORD}

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8092:8080
    networks:
      - backupnet
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=nette

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on: 
      - mariadb
    ports:
      - 8017:80
    networks:
      - backupnet
    volumes:
      - /data/docker/nextcloud/www/html:/var/www/html
      - /data/docker/nextcloud/www/html/custom_apps:/var/www/html/custom_apps
      - /data/docker/nextcloud/www/html/config:/var/www/html/config
      - ${DATAROOT}/nextcloud:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudusr
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
      - MYSQL_HOST=mariadb

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /data/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    networks:
      - backupnet
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  backupnet:
#    name: backupnet
    driver: bridge