version: '3.5'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/portainer:/data

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
#    ports:
#      - 3306:3306
    networks:
      - backupnet
    volumes:
      - ${DATAROOT}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudusr
      - MYSQL_PASSWORD=${MYSQLPASSWORD}

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8092:8080
    networks:
      - backupnet
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=nette

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on: 
      - mariadb
    ports:
      - 8091:80
    networks:
      - backupnet
    volumes:
      - /var/docker/nextcloud/www/html:/var/www/html
      - /var/docker/nextcloud/www/html/custom_apps:/var/www/html/custom_apps
      - /var/docker/nextcloud/www/html/config:/var/www/html/config
      - ${DATAROOT}/nextcloud:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudusr
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
      - MYSQL_HOST=mariadb

networks:
  backupnet:
#    name: backupnet
    driver: bridge